name: Salesforce to Monday Sync

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'  # 매 1시간마다 실행 (UTC 기준)
  workflow_dispatch:      # 수동 실행 가능

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate secrets
        run: |
          for var in SF_CLIENT_ID SF_CLIENT_SECRET SF_USERNAME SF_PASSWORD MONDAY_TOKEN; do
            if [ -z "${!var}" ]; then
              echo "❌ Missing required secret: $var"
              exit 1
            fi
          done
        env:
          SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
          SF_CLIENT_SECRET: ${{ secrets.SF_CLIENT_SECRET }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          MONDAY_TOKEN: ${{ secrets.MONDAY_TOKEN }}

      - name: Run sync script
        run: python main.py
        env:
          SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
          SF_CLIENT_SECRET: ${{ secrets.SF_CLIENT_SECRET }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          MONDAY_TOKEN: ${{ secrets.MONDAY_TOKEN }}
